### ISSUE TITLE
Cannot retrieve auto-generated english transcript.

### ISSUE THREAD

**Issue by Finalet** [Kakulukian/youtube-transcript#18]
Video in question (https://www.youtube.com/watch?v=XcFOOfqfx3s) has two captions: Chinese and English (auto-generated)

No matter what config I pass, the package always return Chinese captions

```javascript
const transcript = await YoutubeTranscript.fetchTranscript(youtubeUrl, { country: "US", lang: "en" });
```

Output:

```javascript
0: {text: '嗨', duration: 710, offset: 0}
1: {text: '想必大家都对“巴格达电池”很好奇吧', duration: 2820, offset: 710}
...
```

What could be the issue here?

**Comment by Kakulukian** [comment]
Fixed with 1.2.1
