### ISSUE TITLE
Hello i have a problem Error: [YoutubeTranscript]

### ISSUE THREAD

**Issue by champseo2017** [Kakulukian/youtube-transcript#2]
Error: [YoutubeTranscript] 🚨 TypeError: URL is not a constructor I am using Next js and Express.

![image](https://user-images.githubusercontent.com/32265715/153796918-b8ba68ff-c745-4e85-ad12-6536bfba79f9.png)

**Comment by dominiczy** [comment]
Getting the same error, any updates?

**Comment by danielgoodwin97** [comment]
I only get this issue when using the URL. If I just use the ID then it's fine.

**Comment by naladda** [comment]
Getting this error event with video id

**Comment by chase-clingman** [comment]
Solution?

**Comment by chinmay021** [comment]
try this :
import YoutubeTranscript from 'youtube-transcript';

YoutubeTranscript.default.fetchTranscript('_cY5ZD9yh2I').then(console.log);

**Comment by 9und30** [comment]
anyone found a fix yet?

**Comment by champseo2017** [comment]
Thank you very much, I will try this method. @naladda

**Comment by Kakulukian** [comment]
Related to https://github.com/ethanent/phin/issues/50, you need to polyfill Url primitive to use in a frontend app. I'll think about removing this dependency to use fetch

**Comment by pedrorocha-net** [comment]
Is anyone able to use this package? Not working for me at all, because of this error.

**Comment by satpalsr** [comment]
Hey @Kakulukian, Any update on this?

**Comment by bvschwartz** [comment]
This module only works on backend server running nodejs.
