### ISSUE TITLE
Handle 'Unauthorized' response

### ISSUE THREAD

**Issue by chr15m** [Kakulukian/youtube-transcript#22]
Video with id `v-YbL4rLdaY` throws this error:

```
SyntaxError: Unexpected token 'U', "Unauthorized" is not valid JSON
```

Would be good to be able to access the response to inspect it when thrown.

**Comment by chr15m** [comment]
This error came from a different library, sorry for the noise.

**Comment by Medullitus** [comment]
How did you fix that ?? @chr15m

**Comment by chr15m** [comment]
I replaced the other library with my own code with different error handling.

**Comment by Medullitus** [comment]
But how are you doing this? I think our developer assumes that we're also developers, so they're not fixing the plugin, and we have to do it ourselves. Can you help?

**Comment by chr15m** [comment]
No I can't sorry. You should pay somebody else to do this work.

**Comment by Medullitus** [comment]
OK!
