### ISSUE TITLE
How do the durations work?

### ISSUE THREAD

**Issue by Donald646** [Kakulukian/youtube-transcript#37]
Is it just me or are the durations pretty off, this is leading my model to producing incorrect results. I'm assuming that the time stamp for a certain text is the sum of the durations before it right?

**Comment by tainguyenphat74** [comment]
Hi @Donald646 , @Kakulukian 
I have the same misunderstanding about duration work? How does it work? I can track when the speaker just finished speaking, can we pause the video?
