### ISSUE TITLE
Please add example.

### ISSUE THREAD

**Issue by nguyenlinhnttu** [Kakulukian/youtube-transcript#5]
Hello
This is great library. So i am a newbie, i have a problem.
`static fetchTranscript(videoId: string, config?: TranscriptConfig)`
How to create config for this function, and how i can get list lang supported
Can you add a example?
Thanks

**Comment by luke-z** [comment]
The default config is 

```
{
  lang: 'fr',
  country: 'FR'
}
```

So you can pass such an object with the new values you need.

You can try it with a video such as this https://www.youtube.com/watch?v=74ijsBhbxSQ which has multiple subtitles.
For me it was enough to use the `lang` key.

To get all the available captions you can look for the `captionTracks` in the source of the video page. Using some sort of scraper you can get the values :)
