### ISSUE TITLE
YouTube regex too lax

### ISSUE THREAD

**Issue by yousefamar** [Kakulukian/youtube-transcript#6]
First, thanks for the great work, you saved me a lot of time!

Just a heads up: your YouTube regex ([here](https://github.com/Kakulukian/youtube-transcript/blob/master/src/index.ts#L4)) is a bit too loose. It will match URLs like `https://example.dev/`. I found this out the hard way when my server kept choking. I think it would be great to use a different regex.

**Comment by Kakulukian** [comment]
Thank you for notifying me, I have released version `1.0.6` of the package. This updated version includes a stricter regex to parse YouTube link 👍
