### ISSUE TITLE
Uncaught (in promise) Error: [YoutubeTranscript] 🚨 TypeError: URL is not a constructor

### ISSUE THREAD

**Issue by harshuchilzy** [Kakulukian/youtube-transcript#9]
When I try to fetch a transcript i get this error

console.log(YoutubeTranscript.fetchTranscript('W5ESi5qDxCY', {
    lang: 'en'
}))

**Comment by hamza-al** [comment]
same issue

**Comment by joshcho96** [comment]
same issue.

**Comment by joshcho96** [comment]
I found the reason to this problem. This package does not work on the Client Web (React CRA). Only works on backend.

**Comment by harshuchilzy** [comment]
> I found the reason to this problem. This package does not work on the Client Web (React CRA). Only works on backend.

Ahhh right :(

**Comment by ashishbamania** [comment]
Is there a way around it?
